server:
  port: ${API_PORT:8990}
  jetty:
    min-threads: 8
    max-threads: 200
    thread-idle-timeout: 60000
  servlet:
    context-path: "/shop_kafka_consumer/api"
  # For include message error to http response!!!
  error:
    include-message: always

spring:
  application:
    name: shop_kafka_consumer

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:192.168.1.20:9092}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
